### ISSUE TITLE
Difficulty installing with anaconda and pip

### ISSUE THREAD

**Issue by fredcallaway** [wmayner/pyemd#5]
__Note:__ I was able to solve the problem by installing from source. I'm posting just to document the issue.

I'm running python3.5 with the most recent distribution of anaconda
```
~ $  python --version
Python 3.5.0 :: Anaconda 2.4.0 (x86_64)
```

I get the following error when I try to install premed
```
~ $  pip install --no-cache-dir pyemd
Collecting pyemd
  Downloading pyemd-0.2.0.tar.gz (52kB)
    100% |████████████████████████████████| 53kB 4.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/z4/8yrkxb250h3d9psym1bmqvgw0000gw/T/pip-build-g8fo_tbk/pyemd/setup.py", line 44, in <module>
        extensions = cythonize(extensions)
      File "/Users/fred/anaconda/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 758, in cythonize
        aliases=aliases)
      File "/Users/fred/anaconda/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 651, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/fred/anaconda/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pyemd/emd.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/z4/8yrkxb250h3d9psym1bmqvgw0000gw/T/pip-build-g8fo_tbk/pyemd
```

I can install fine using the source on github. I can also install from pip using the standard python 3.4 distribution (haven't tried the standard python 3.5)

**Comment by wmayner** [comment]
This has been fixed in v0.3.0.
